apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jhipster-app
  template:
    metadata:
      labels:
        app: jhipster-app
    spec:
      containers:
      - name: jhipster-app
        image: jhipster-app:latest    # Jenkins remplacera avec kubectl set image
        imagePullPolicy: Never        # IMPORTANT pour Minikube
        ports:
        - containerPort: 8080
